version: '3.8'
services:
  funasr:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        HTTP_PROXY: ${HTTP_PROXY}
    image: paidax/funasr_python:0.4.4
    runtime: nvidia
    ports:
      - 9527:9527
    command: uvicorn main:app --host 0.0.0.0 --port 9527
